# Generated by Django 4.1 on 2024-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenddt',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
