# Generated by Django 4.1 on 2024-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_diendan_headline_remove_diendan_sub_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diendan',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='diendan',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
