# Generated by Django 4.1 on 2024-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenddt',
            name='hoten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
