# Generated by Django 4.1 on 2024-06-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_studenddt_hoten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diendancomment',
            options={'ordering': ['-id']},
        ),
    ]
